version: "3.8"
services:
  rabbitmq1:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq1
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
      - RABBITMQ_NODE_NAME=rabbit@rabbitmq1
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq.conf
      - RABBITMQ_ERLANG_COOKIE=12345
      - RABBITMQ_NODE_PORT=5672      
    volumes:
      - ./rabbitmq/config:/config:ro
    ports:
      - 15672:15672
      - 5672:5672
  rabbitmq2:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq2
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
      - RABBITMQ_NODE_NAME=rabbit@rabbitmq2
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq.conf
      - RABBITMQ_ERLANG_COOKIE=12345
      - RABBITMQ_NODE_PORT=5672      
    volumes:
      - ./rabbitmq/config:/config:ro
  rabbitmq3:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq3
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
      - RABBITMQ_NODE_NAME=rabbit@rabbitmq3
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq.conf
      - RABBITMQ_ERLANG_COOKIE=12345
      - RABBITMQ_NODE_PORT=5672      
    volumes:
      - ./rabbitmq/config:/config:ro
